apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs-agent-py
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dealwallet1/cs_agent-py.git
    targetRevision: HEAD
    path: argomanifest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
